server:
    port: 8082
    servlet:
        context-path: /
logging:
    level:
        com.x.*: debug
    #path: C\:\\Users\\zwj\\Desktop
    path: /data/logs/x
    file: x.log
    config: classpath:logback-spring.xml







